
package university;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;

public class Cours extends javax.swing.JFrame {
    
    int choose;
    
    Connection con = null;
    PreparedStatement com = null;
    ResultSet rst = null;

    Courses c = new Courses();
    
    public Cours() {
        initComponents();
        c.setVisible(true);
        
        setIconImage(new ImageIcon(getClass().getResource("image/university-331279047401mXI3.jpg")).getImage());
        
        
        InsertNameProfessor();
        
        choose = MainPage.chC;
        
        if(choose == 2){
            this.setTitle("Update a Course");
            jLabel4.setText("Update a Course");
            jButton1.setText("UPDATE");
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jComboBox1.setEnabled(false);
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jButton2.setEnabled(true);
            
            
        }else if(choose == 3){
            this.setTitle("Delete a Course");
            jLabel4.setText("Delete a Course");
            jButton1.setText("DELETE");
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jComboBox1.setEnabled(false);
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add a Course");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(212, 208, 208));
        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(18, 72, 236));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(840, -10, 200, 620);

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(18, 72, 236));
        jLabel12.setText("Professor of This course");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(380, 430, 190, 30);

        jTextField1.setBackground(new java.awt.Color(212, 208, 208));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(350, 90, 300, 40);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(212, 208, 208));
        jLabel4.setText("Add a Course");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 430, 60);

        jTextField2.setBackground(new java.awt.Color(212, 208, 208));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(350, 180, 380, 40);

        jTextField3.setBackground(new java.awt.Color(212, 208, 208));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(350, 270, 380, 40);

        jTextField4.setBackground(new java.awt.Color(212, 208, 208));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(350, 360, 380, 40);

        jComboBox1.setBackground(new java.awt.Color(212, 208, 208));
        jComboBox1.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(18, 72, 236));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(380, 460, 230, 40);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 72, 236));
        jLabel2.setText("Course_NR");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 70, 170, 20);

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(18, 72, 236));
        jLabel14.setText("Course Name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(350, 160, 170, 20);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(18, 72, 236));
        jLabel15.setText("Hours_NR");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(350, 250, 170, 20);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(18, 72, 236));
        jRadioButton1.setText("First semester");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(660, 440, 150, 25);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(18, 72, 236));
        jRadioButton2.setText("Second semester");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(660, 510, 150, 25);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 3, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(18, 72, 236));
        jLabel13.setText("Price (1H)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(350, 340, 170, 20);

        jButton2.setBackground(new java.awt.Color(212, 208, 208));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(18, 72, 236));
        jButton2.setText("Get");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(660, 90, 70, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/image/black background 7.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1060, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1034, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        switch (choose) {
            case 1:
                Insert();
                break;
            case 2:
                Update();
                break;
            default:
                Delete();
                break;
        }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
         if(evt.getKeyCode() == evt.VK_ENTER && choose == 2){
             Quick();  
        }      
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Quick();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       c.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void Insert() {
         String Err = "You forgot to enter the following data :"+"\n\n";
            
            if(jTextField1.getText().equals("")){
                Err += "Course Number\n";
            }
            if(jTextField2.getText().equals("")){
                Err += "Course Name\n";
            }
            if(jTextField3.getText().equals("")){
                Err += "Hours Number\n";
            }
            if(jTextField4.getText().equals("")){
                Err += "Price for one Hour\n";
            }
            
            if(jComboBox1.getSelectedIndex() == -1){
                Err += "Doctor of This course\n";
            }
            
            if(!jRadioButton1.isSelected()&&!jRadioButton2.isSelected()){
                Err += "Semester \n";
            }
            
            int semester = 1;
            if(jRadioButton2.isSelected()){
                semester = 2;
            }
            
            
            
             if(!jTextField1.getText().equals("") &&
               !jTextField2.getText().equals("") &&
               !jTextField3.getText().equals("")&&
               !jTextField4.getText().equals("")&&
               jComboBox1.getSelectedIndex() != -1 &&
               (jRadioButton1.isSelected() || jRadioButton2.isSelected())){
                  
                                       try {
                                          int nr = Integer.parseInt(jTextField1.getText());
                                       } catch (NumberFormatException e) {
                                           JOptionPane.showMessageDialog(this, "Please Enter an Integer Number !");
                                       }
                                       
                                       
                 try {
              
                                       
                 con = ConnectionDataBase.connect();
                 com = con.prepareStatement("select*from Course where idCourse = '"+Integer.parseInt(jTextField1.getText())+"'");
                 rst = com.executeQuery();
                 if(!rst.next()){
                      com = con.prepareStatement("insert into Course values('"+Integer.parseInt(jTextField1.getText())+"','"
                                                                                 +jTextField2.getText()+"','"
                                                                                 +Integer.parseInt(jTextField3.getText())+"','"
                                                                                 +jComboBox1.getSelectedItem()+"','"
                                                                                 +Integer.parseInt(jTextField4.getText())+"','"
                                                                                 +semester+"')");

                        com.execute();
                        
                        JOptionPane.showMessageDialog(null,"The add process has been completed","Course has been added",JOptionPane.INFORMATION_MESSAGE);
                        Clear();
                        
                        
                 }else{
                        JOptionPane.showMessageDialog(null,"Course Number is Already Exist ", "ADD FAILED!",2);
                 }
                 
                 
             } catch (SQLException ex) {
             }finally{
                 try {
                     con.close();
                 } catch (SQLException ex) {
                 }
             }
                 
                 
            
          
            }else{     
              JOptionPane.showMessageDialog(null,Err, "Data Lost",2);
            } 
    }        

    private void Update() {
        
            String Err = "You forgot to enter the following data :"+"\n\n";
            
            if(jTextField2.getText().equals("")){
                Err += "Course Name\n";
            }
            if(jTextField3.getText().equals("")){
                Err += "Hours Number\n";
            }
            if(jTextField4.getText().equals("")){
                Err += "Price for one Hour\n";
            }
            
            if(jComboBox1.getSelectedIndex() == -1){
                Err += "Doctor of This course\n";
            }
            
            if(!jRadioButton1.isSelected()&&!jRadioButton2.isSelected()){
                Err += "Semester \n";
            }
            
            int semester = 1;
            if(jRadioButton2.isSelected()){
                semester = 2;
            }
               
             
            if(!jTextField2.getText().equals("") &&
               !jTextField3.getText().equals("")&&
               !jTextField4.getText().equals("")&&
               jComboBox1.getSelectedIndex() != -1 &&
               (jRadioButton1.isSelected() || jRadioButton2.isSelected())){
                 
                    try {
                    con = ConnectionDataBase.connect();
                    com = con.prepareStatement("update Course set nameC = '"+jTextField2.getText()+"' , hours = '"
                                                                             +Integer.parseInt(jTextField3.getText())+"' , nameP = '"
                                                                             +jComboBox1.getSelectedItem()+"', salaryForHour = '"
                                                                             +Integer.parseInt(jTextField4.getText())+"', semester = '"+semester+"' where idCourse = '"
                                                                             +Integer.parseInt(jTextField1.getText())+"'");
                    com.execute();
                    JOptionPane.showMessageDialog(null,"The update process has been completed","Course has been updated",JOptionPane.INFORMATION_MESSAGE);
                    
                    Clear();
                   
                    
                    jTextField1.setEnabled(true);
                    jTextField2.setEnabled(false);
                    jTextField3.setEnabled(false);
                    jTextField4.setEnabled(false);
                    jComboBox1.setEnabled(false);
                    jRadioButton1.setEnabled(false);
                    jRadioButton2.setEnabled(false);
                    

                } catch (SQLException ex) {
                }finally{
                    try {
                        con.close();
                    } catch (SQLException ex) {
                    }
                }
     
            }else{     
              JOptionPane.showMessageDialog(null,Err, "Data Lost",2);
            } 
    }

    private void Delete() {

           String Err = "Please enter the following data :"+"\n\n";
           
           if(jTextField1.getText().equals("")){
                Err += "Course Number\n";
            }
             if(!jTextField1.getText().equals("")){
                 
                                       try {
                                          int nr = Integer.parseInt(jTextField1.getText());
                                       } catch (NumberFormatException e) {
                                           JOptionPane.showMessageDialog(this, "Please Enter an Integer Number !");
                                       }
                                       
                                       
                 try {
                    con = ConnectionDataBase.connect();
                    com = con.prepareStatement("select * from Course where idCourse ='"+Integer.parseInt(jTextField1.getText())+"'");
                    rst = com.executeQuery();
                   
                   
                   if(rst.next()){
                   String CursN = rst.getString(2);
                   int p =  JOptionPane.showConfirmDialog(null, "Do you really want to delete "+CursN+" from Database ?!", " Confirm! " , JOptionPane.YES_NO_OPTION);
                        if(p == 0){

                            com = con.prepareStatement("delete * from Course where idCourse ='"+Integer.parseInt(jTextField1.getText())+"'");
                            com.execute();
                            JOptionPane.showMessageDialog(null,"The Delete process has been completed","Course has been Deleted ",JOptionPane.INFORMATION_MESSAGE);
                            jTextField1.setText("");
                            
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null,"Course Number is Not Exist ", "Not Exist",2); 
                    }
    
                    
                }catch(SQLException ex){       
                }finally{
                   try {
                       con.close();
                   } catch (SQLException ex) {
                   }
                }
                 
                 
                 
                 
            
          
            }else{     
              JOptionPane.showMessageDialog(null,Err, "Data Lost",2);
            } 
    }
    
        private void Clear() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
        jComboBox1.setSelectedIndex(-1);
        
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
    }

    private void InsertNameProfessor() {
        
        try {
            con = ConnectionDataBase.connect();
            com = con.prepareStatement("select nameP from Professor");
            rst = com.executeQuery();
            
            while(rst.next()){
                jComboBox1.addItem(rst.getString("nameP"));
            }
            jComboBox1.setSelectedIndex(-1);
        } catch (SQLException ex) {
        }finally{
                   try {
                       con.close();
                   } catch (SQLException ex) {
                   }
        }

    }

    private void Quick() {
        if(jTextField1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Course Number field is empty" , "Empty",2);
            }else{
            
                                        try {
                                          int nr = Integer.parseInt(jTextField1.getText());
                                       } catch (NumberFormatException e) {
                                           JOptionPane.showMessageDialog(this, "Please Enter an Integer Number !");
                                       }
                try {
                     
                    con = ConnectionDataBase.connect();
                    com = con.prepareStatement("select * from Course where idCourse = '"+Integer.parseInt(jTextField1.getText())+"'");
                    rst = com.executeQuery();
                    
                    if(rst.next()){
                        jTextField1.setEnabled(false);
                        
                        
                        jTextField2.setText(rst.getString(2));
                        jTextField2.setEnabled(true);
                        
                        jTextField3.setText(rst.getString(3));
                        jTextField3.setEnabled(true);
                        
                        String ProfN = rst.getString(4);
                        jComboBox1.setEnabled(true);
                        if(ProfN.equals(" ")){
                            jComboBox1.setSelectedIndex(-1);
                        }else{
                            jComboBox1.setSelectedItem(ProfN);
                        }
                        
                        
                        
                        jTextField4.setText(rst.getString(5));
                        jTextField4.setEnabled(true);
                        
                        int semester = Integer.parseInt(rst.getString(6));
                      
                            jRadioButton1.setSelected(true);
                            
                        if(semester == 2){
                            jRadioButton2.setSelected(true);
                        }
                        
                        jRadioButton1.setEnabled(true);
                        jRadioButton2.setEnabled(true);
                        
                        
                    }else{
                            JOptionPane.showMessageDialog(null,"Course Number is Not Exist ", "Not Exist",2); 
                    }
                } catch (SQLException ex) {
                    
                } finally{
                    try {
                        con.close();
                    } catch (SQLException ex) {
                    }
                }
        }

    }
}
